name: todo_app_bloc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.8.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  uuid: ^4.4.2
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar-icon.jpg
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/static/Urbanist-Regular.ttf
        - asset: assets/fonts/static/Urbanist-Bold.ttf
          weight: 500
        - asset: assets/fonts/static/Urbanist-Italic.ttf
          style: italic

  


